# Generated by Django 3.2.5 on 2021-07-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('image', models.CharField(default=None, max_length=500)),
                ('audio_language', models.CharField(default=None, max_length=50)),
                ('run_time_mins', models.PositiveIntegerField(default=None)),
                ('year', models.PositiveIntegerField(default=None)),
                ('views_count', models.PositiveIntegerField(default=None)),
                ('worth_a_watch', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
