# Generated by Django 3.2.6 on 2021-08-05 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('image', models.CharField(default=None, max_length=300)),
                ('video', models.CharField(default=None, max_length=300)),
                ('audio_language', models.CharField(default=None, max_length=50)),
                ('run_time_mins', models.PositiveIntegerField(default=None)),
                ('year', models.PositiveIntegerField(default=None)),
                ('views_count', models.PositiveIntegerField(default=None)),
                ('worth_a_watch', models.BooleanField(default=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
