# Generated by Django 3.2.5 on 2021-07-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_run_time_mins_movie_run_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='run_time',
            new_name='run_time_mins',
        ),
    ]
