# Generated by Django 3.2.5 on 2021-07-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='video',
        ),
    ]
