# Generated by Django 3.2.5 on 2021-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_image_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
